/**
 * Static management-dashboard data used when DEMO_MODE is on (DB unlinked).
 */
import type {
    FeedItem,
    EventItem,
    MemberItem,
    ResourceItem,
    ProjectItem,
    InquiryItem,
    FAQItem,
    ActionItem,
    BudgetItem,
    OrgSettingsDoc,
    EboardTaskItem,
    EboardCalendarEventItem,
} from "@/hooks/useFirestore";
import type { StartupItem } from "@/lib/startup-document";
import { FEATURED_STARTUPS } from "@/lib/demo-data";

const now = Date.now();
const daysFromNow = (d: number) => {
    const date = new Date(now + d * 86400000);
    return date.toISOString().slice(0, 10);
};

export const DEMO_USER = {
    uid: "demo-admin",
    email: "demo@etower.babson.edu",
    displayName: "Alex Rivera",
    photoURL: null as string | null,
};

export const DEMO_PROFILE = {
    uid: DEMO_USER.uid,
    email: DEMO_USER.email,
    displayName: DEMO_USER.displayName,
    photoURL: null as string | null,
    role: "president" as const,
    residency: "resident" as const,
    status: "approved" as const,
    standoutSkill: "Product Strategy",
    skills: ["Product", "Fundraising", "Leadership"],
    onboarded: true,
    openToMentorship: false,
    linkedin: "https://linkedin.com/in/example",
    graduationYear: "2026",
    engagementMetrics: {
        attendanceRate: 92,
        projectsCompleted: 3,
        uploadsCount: 5,
        pitchesSubmitted: 2,
    },
};

export const DEMO_MEMBERS: MemberItem[] = [
    {
        id: "demo-admin",
        name: "Alex Rivera",
        email: "demo@etower.babson.edu",
        role: "president",
        residency: "resident",
        status: "approved",
        photoURL: null,
        standoutSkill: "Product Strategy",
        projects: 3,
        uploads: 5,
        attendance: "92%",
        joinDate: "Sep 12, 2024",
        linkedin: "https://linkedin.com/in/example",
        bio: "Building community and ventures at eTower.",
        skills: ["Product", "Fundraising", "Leadership"],
        openToMentorship: false,
        birthday: "2003-04-12",
        graduationYear: "2026",
    },
    {
        id: "m2",
        name: "Jordan Lee",
        email: "jlee@babson.edu",
        role: "vp-events",
        residency: "resident",
        status: "approved",
        photoURL: null,
        standoutSkill: "Event Production",
        projects: 2,
        uploads: 3,
        attendance: "88%",
        joinDate: "Sep 12, 2024",
        linkedin: null,
        bio: "VP of Events — workshops and community nights.",
        skills: ["Operations", "Marketing"],
        openToMentorship: false,
        birthday: "2004-01-20",
        graduationYear: "2027",
    },
    {
        id: "m3",
        name: "Sam Patel",
        email: "spatel@babson.edu",
        role: "member",
        residency: "associate",
        status: "approved",
        photoURL: null,
        standoutSkill: "Full-Stack Dev",
        projects: 4,
        uploads: 8,
        attendance: "75%",
        joinDate: "Jan 15, 2025",
        linkedin: null,
        bio: null,
        skills: ["React", "TypeScript", "Firebase"],
        openToMentorship: false,
        birthday: null,
        graduationYear: "2027",
    },
    {
        id: "m4",
        name: "Casey Nguyen",
        email: "cnguyen@babson.edu",
        role: "alumni",
        residency: "alumni",
        status: "approved",
        photoURL: null,
        standoutSkill: "Growth Marketing",
        projects: 6,
        uploads: 2,
        attendance: "—",
        joinDate: "Sep 1, 2021",
        linkedin: "https://linkedin.com/in/example",
        bio: "Founder alum — open to mentoring residents.",
        skills: ["Growth", "Sales"],
        openToMentorship: true,
        birthday: "2000-08-03",
        graduationYear: "2024",
    },
    {
        id: "m5",
        name: "Riley Brooks",
        email: "rbrooks@babson.edu",
        role: "member",
        residency: "resident",
        status: "approved",
        photoURL: null,
        standoutSkill: "Design",
        projects: 1,
        uploads: 4,
        attendance: "95%",
        joinDate: "Sep 5, 2025",
        linkedin: null,
        bio: "Product design and brand systems.",
        skills: ["Figma", "Brand"],
        openToMentorship: false,
        birthday: "2005-11-11",
        graduationYear: "2028",
    },
];

export const DEMO_FEED: FeedItem[] = [
    {
        id: "f1",
        type: "announcement",
        actorId: "demo-admin",
        actorName: "Alex Rivera",
        description: "pinned a welcome note for new residents this semester",
        targetId: null,
        targetName: null,
        pinned: true,
        pinnedBy: "demo-admin",
        createdAt: "2 hours ago",
        _createdAt: new Date(now - 7200000).toISOString(),
    },
    {
        id: "f2",
        type: "resource_upload",
        actorId: "m2",
        actorName: "Jordan Lee",
        description: "uploaded Pitch Deck Template to the Resource Library",
        targetId: null,
        targetName: null,
        pinned: false,
        pinnedBy: null,
        createdAt: "1 day ago",
        _createdAt: new Date(now - 86400000).toISOString(),
    },
    {
        id: "f3",
        type: "milestone_update",
        actorId: "m3",
        actorName: "Sam Patel",
        description: "Accessibility Checker reached 45% milestone progress",
        targetId: "p1",
        targetName: "Accessibility Checker",
        pinned: false,
        pinnedBy: null,
        createdAt: "2 days ago",
        _createdAt: new Date(now - 172800000).toISOString(),
    },
    {
        id: "f4",
        type: "member_join",
        actorId: "m5",
        actorName: "Riley Brooks",
        description: "joined eTower",
        targetId: null,
        targetName: null,
        pinned: false,
        pinnedBy: null,
        createdAt: "5 days ago",
        _createdAt: new Date(now - 432000000).toISOString(),
    },
];

export const DEMO_EVENTS: EventItem[] = [
    {
        id: "e1",
        title: "Weekly Community Dinner",
        description: "Resident dinner and open updates on ventures.",
        date: daysFromNow(1),
        time: "18:30 – 20:00",
        startTime: "18:30",
        endTime: "20:00",
        location: "Van Winkle Hall",
        type: "meeting",
        status: "upcoming",
        attendees: ["demo-admin", "m2", "m5"],
        attendance: [],
        attendanceByDate: {},
        maxAttendees: 30,
        tags: ["community"],
        featured: false,
        createdBy: "demo-admin",
        housingHostUids: [],
        createdAt: daysFromNow(-20),
        recurrence: { interval: "weekly", count: 8 },
    },
    {
        id: "e2",
        title: "Founder Fireside",
        description: "Alumni founder shares lessons from scaling.",
        date: daysFromNow(4),
        time: "17:00 – 18:30",
        startTime: "17:00",
        endTime: "18:30",
        location: "Innovation Hub",
        type: "workshop",
        status: "upcoming",
        attendees: ["demo-admin", "m3"],
        attendance: [],
        attendanceByDate: {},
        maxAttendees: 40,
        tags: ["alumni", "speaker"],
        featured: true,
        createdBy: "m2",
        housingHostUids: [],
        createdAt: daysFromNow(-10),
        recurrence: null,
    },
    {
        id: "e3",
        title: "Pitch Practice Night",
        description: "Optional 5-minute pitch reps with peer feedback.",
        date: daysFromNow(9),
        time: "19:00 – 21:00",
        startTime: "19:00",
        endTime: "21:00",
        location: "Tower Lounge",
        type: "workshop",
        status: "upcoming",
        attendees: [],
        attendance: [],
        attendanceByDate: {},
        maxAttendees: 20,
        tags: ["pitch"],
        featured: false,
        createdBy: "m2",
        housingHostUids: [],
        createdAt: daysFromNow(-5),
        recurrence: null,
    },
];

export const DEMO_RESOURCES: ResourceItem[] = [
    {
        id: "r1",
        title: "Pitch Deck Template",
        description: "Clean template for investor and demo day pitches.",
        type: "template",
        tier: "official",
        phase: "beginner",
        topics: ["Pitch", "Fundraising"],
        views: 120,
        uploadedBy: "Jordan Lee",
        uploadedById: "m2",
        date: "Mar 1, 2026",
        fileUrl: null,
        approved: true,
    },
    {
        id: "r2",
        title: "Getting Started with Next.js",
        description: "Routing, data fetching, and deployment basics.",
        type: "guide",
        tier: "official",
        phase: "beginner",
        topics: ["Next.js", "React"],
        views: 142,
        uploadedBy: "E-Board",
        uploadedById: null,
        date: "Feb 12, 2026",
        fileUrl: null,
        approved: true,
    },
    {
        id: "r3",
        title: "Customer Interview Script",
        description: "Questions for early discovery calls.",
        type: "guide",
        tier: "community",
        phase: "intermediate",
        topics: ["Research", "Customers"],
        views: 67,
        uploadedBy: "Sam Patel",
        uploadedById: "m3",
        date: "Jan 20, 2026",
        fileUrl: null,
        approved: true,
    },
];

export const DEMO_PROJECTS: ProjectItem[] = [
    {
        id: "p1",
        name: "Accessibility Checker",
        description: "Browser extension for WCAG checks and suggestions.",
        status: "in-progress",
        teamMembers: [
            { uid: "m3", role: "lead", name: "Sam Patel" },
            { uid: "m5", role: "designer", name: "Riley Brooks" },
        ],
        githubUrl: "https://github.com/example/a11y",
        liveUrl: null,
        coverImage: null,
        gallery: [],
        content: "",
        tasks: [
            { id: "t1", title: "Audit rules engine", completed: true },
            { id: "t2", title: "UI polish", completed: false },
        ],
        updatedAt: "2 days ago",
        createdAt: "Jan 10, 2026",
        clientVisible: true,
    },
    {
        id: "p2",
        name: "Volunteer Portal",
        description: "Matching residents with local nonprofit opportunities.",
        status: "complete",
        teamMembers: [
            { uid: "demo-admin", role: "lead", name: "Alex Rivera" },
            { uid: "m3", role: "developer", name: "Sam Patel" },
        ],
        githubUrl: null,
        liveUrl: "https://example.com",
        coverImage: null,
        gallery: [],
        content: "",
        tasks: [],
        updatedAt: "1 week ago",
        createdAt: "Oct 1, 2025",
        clientVisible: true,
    },
];

export const DEMO_ACTION_ITEMS: ActionItem[] = [
    {
        id: "a1",
        title: "RSVP for Founder Fireside",
        description: "Confirm attendance by Thursday.",
        deadline: daysFromNow(3),
        type: "external",
        link: null,
        completedBy: [],
        createdAt: "Mar 10, 2026",
        createdBy: "demo-admin",
    },
    {
        id: "a2",
        title: "Update your profile skills",
        description: "Help match mentors and project teams.",
        deadline: daysFromNow(7),
        type: "form",
        link: "/profile",
        completedBy: [],
        createdAt: "Mar 9, 2026",
        createdBy: "demo-admin",
    },
];

export const DEMO_INQUIRIES: InquiryItem[] = [
    {
        id: "i1",
        question: "How do I apply for residency next year?",
        category: "housing",
        status: "pending",
        date: "2 days ago",
        askedBy: "Prospective Student",
        reply: null,
        repliedBy: null,
    },
];

export const DEMO_FAQ: FAQItem[] = [
    {
        id: "faq1",
        question: "Who can join eTower?",
        answer: "Babson students passionate about entrepreneurship — applications are reviewed on a rolling basis.",
        createdAt: "Jan 2026",
    },
];

export const DEMO_ORG_SETTINGS: OrgSettingsDoc = {
    id: "club",
    fiscalTerm: "spring",
    fiscalYearTwoDigit: "26",
};

export const DEMO_BUDGETS: BudgetItem[] = [];

export const DEMO_EBOARD_TASKS: EboardTaskItem[] = [
    {
        id: "t1",
        title: "Finalize spring events calendar",
        description: "Lock dates for dinners and speakers.",
        status: "in_progress",
        priority: "high",
        assigneeUids: ["m2", "demo-admin"],
        dueDate: daysFromNow(5),
        createdBy: "demo-admin",
        createdAt: "Mar 1, 2026",
        updatedAt: "Mar 8, 2026",
        completedAt: null,
    },
    {
        id: "t2",
        title: "Review newsletter draft",
        description: "Monthly community update.",
        status: "todo",
        priority: "normal",
        assigneeUids: ["demo-admin"],
        dueDate: daysFromNow(10),
        createdBy: "demo-admin",
        createdAt: "Mar 5, 2026",
        updatedAt: "Mar 5, 2026",
        completedAt: null,
    },
];

export const DEMO_EBOARD_CALENDAR: EboardCalendarEventItem[] = [
    {
        id: "ec1",
        title: "E-Board Sync",
        description: "Weekly leadership check-in",
        startDate: daysFromNow(2),
        endDate: null,
        startTime: "12:00",
        endTime: "13:00",
        allDay: false,
        location: "Zoom",
        attendeeUids: ["demo-admin", "m2"],
        createdBy: "demo-admin",
        createdAt: "Mar 1, 2026",
        updatedAt: "Mar 1, 2026",
    },
];

export const DEMO_STARTUPS: StartupItem[] = FEATURED_STARTUPS.map((s, i) => ({
    id: s.id,
    name: s.name,
    companyOverview: s.overview,
    founderStory: "",
    founders: s.founder,
    foundedYear: String(2020 + (i % 5)),
    businessCategory: s.category,
    website: null,
    instagramUrl: null,
    linkedinCompanyUrl: null,
    logoUrl: null,
    submittedByUid: "m4",
    submitterName: s.founder,
    submitterGraduationYear: "2024",
    submitterPhotoURL: null,
    status: "approved" as const,
    reviewedByUid: null,
    reviewedByName: null,
    reviewedAt: "",
    createdAt: "Jan 1, 2025",
}));

export const DEMO_NEWSLETTER = [
    { id: "n1", email: "friend@example.com", source: "popup", date: "Mar 10, 2026" },
    { id: "n2", email: "alum@example.com", source: "join-modal", date: "Mar 8, 2026" },
];

export function getDemoCollection<T extends { id: string }>(name: string): T[] {
    const map: Record<string, unknown[]> = {
        activityFeed: DEMO_FEED,
        events: DEMO_EVENTS,
        users: DEMO_MEMBERS,
        resources: DEMO_RESOURCES,
        projects: DEMO_PROJECTS,
        inquiries: DEMO_INQUIRIES,
        faq: DEMO_FAQ,
        actionItems: DEMO_ACTION_ITEMS,
        startups: DEMO_STARTUPS,
        budgets: DEMO_BUDGETS,
        eboardTasks: DEMO_EBOARD_TASKS,
        eboardCalendarEvents: DEMO_EBOARD_CALENDAR,
        newsletterSubscribers: DEMO_NEWSLETTER,
    };
    return (map[name] ?? []) as T[];
}
